name: CI
on: [push, pull_request]
jobs:
  rubocop-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test on ruby ${{ matrix.ruby }} and rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7']
        rails: ['5.2.3', '6.0.0', '6.1.0']
    env:
      CI: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Do some action caching
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Run Rake with Rails ${{ matrix.rails }}
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rspec

  coverage:
    name: "Check coverage"
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Do some action caching
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-2.7-6.1.0-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-2.7-6.1.0-
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundler
        run: gem install bundler
      - name: Run bundler
        env:
          RAILS_VERSION: 6.1.0
        run: |
          bundle install --jobs 4 --retry 3
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
        with:
          coverageCommand: bundle exec rspec
          debug: true