name: CI
on: [push, pull_request]
jobs:
  rubocop-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
s
  test:
    name: Test on ruby ${{ matrix.ruby }} and rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7']
        rails: ['5.2.3', '6.0.0', '6.1.0']
    env:
      CI: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Do some action caching
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Run Rake with Rails ${{ matrix.rails }}
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rspec